swagger: "2.0"
info:
  description: "Descripción de una API para realizar operaciones CRUD sobre clientes, correspondiente al ejercicio 10 práctica 5"
  version: "1.0.0"
  title: "CRUD Cientes"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "pablodanielcocinero@gmail.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/Clientes/v1"
tags:
- name: "cliente"
  description: "Informacion de los clientes"
schemes:
- "https"
- "http"
paths:
  /cliente:
    post:
      tags:
      - "crear cliente"
      summary: "Add a new client to the database"
      description: ""
      operationId: "addClient"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Client object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/cliente"
      responses:
        "405":
          description: "Invalid input"
    put:
      tags:
      - "actualizar cliente"
      summary: "Update an existing client"
      description: ""
      operationId: "updateClient"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Client object that needs to be updated"
        required: true
        schema:
          $ref: "#/definitions/cliente"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
        "405":
          description: "Validation exception"
  /cliente/{dni}:
    get:
      tags:
      - "obtener cliente"
      summary: "Find client by DNI"
      description: "Returns a single client"
      operationId: "getClientById"
      produces:
      - "application/json"
      parameters:
      - name: "dni"
        in: "path"
        description: "DNI of client to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
          "200":
            description: "successful operation"
            schema:
              $ref: "#/definitions/cliente"
          "400":
            description: "Invalid DNI supplied"
          "404":
            description: "Client not found"
    delete:
      tags:
      - "borrar cliente"
      summary: "delete a single client"
      description: ""
      parameters:
      - name: "dni"
        in: "path"
        description: "DNI of client to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: OK
  /cliente/{apellido}/getBySurname:
    get:
      tags:
      - "obtener cliente por apellido"
      summary: "Find client by surname"
      description: "Returns a list of clients"
      operationId: "getClientBySurname"
      produces:
      - "application/json"
      parameters:
      - name: "apellido"
        in: "path"
        description: "surname of clients to return"
        required: true
        type: "string"
        format: "string"
      responses:
          "200":
            description: "successful operation"
            schema:
              $ref: "#/definitions/cliente"
          "400":
            description: "Invalid surname supplied"
          "404":
            description: "Clients not found"
  /cliente/{correo}/getByEmail:
    get:
      tags:
      - "obtener cliente por correo"
      summary: "Find client by email"
      description: "Returns a list of clients"
      operationId: "getClientByEmail"
      produces:
      - "application/json"
      parameters:
      - name: "correo"
        in: "path"
        description: "email of clients to return"
        required: true
        type: "string"
        format: "string"
      responses:
          "200":
            description: "successful operation"
            schema:
              $ref: "#/definitions/cliente"
          "400":
            description: "Invalid email supplied"
          "404":
            description: "Clients not found"
definitions:
  cliente:
    type: "object"
    properties:
      dni:
        type: "integer"
        format: "int64"
      nombre:
        type: "string"
      apellido:
        type: "string"
      telefono:
        type: "string"
      correo:
        type: "string"
      direccion:
        type: "string"
    xml:
      name: "cliente"